"""Leeds Bradford Airport (LBA) destinations — April 2026."""

DESTINATIONS = {
    "LBA": {
        "name": "Leeds Bradford",
        "routes": {
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGO": "Bergen",
            "BJV": "Bodrum",
            "BOJ": "Bourgas",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CLJ": "Cluj-Napoca",
            "CMF": "Chambery",
            "CPH": "Copenhagen",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "EFL": "Kefalonia",
            "EGC": "Bergerac",
            "FAO": "Faro",
            "FCO": "Rome",
            "FNC": "Funchal",
            "FUE": "Fuerteventura",
            "GCI": "Guernsey",
            "GDN": "Gdansk",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HER": "Heraklion",
            "HRG": "Hurghada",
            "IBZ": "Ibiza",
            "JER": "Jersey",
            "JSI": "Skiathos",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KRK": "Krakow",
            "LCA": "Larnaca",
            "LEI": "Almeria",
            "LIG": "Limoges",
            "LPA": "Gran Canaria",
            "MAH": "Menorca",
            "MLA": "Malta",
            "NAP": "Naples",
            "NCE": "Nice",
            "OPO": "Porto",
            "OTP": "Bucharest",
            "PFO": "Paphos",
            "PGF": "Perpignan",
            "PMI": "Palma",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PSA": "Pisa",
            "RAK": "Marrakesh",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "SKG": "Thessaloniki",
            "SPU": "Split",
            "SSH": "Sharm El Sheikh",
            "SZG": "Salzburg",
            "TFS": "Tenerife South",
            "VIE": "Vienna",
            "VRN": "Verona",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "XRY": "Jerez",
            "ZAD": "Zadar",
            "ZTH": "Zante",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
